version: "3"
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    container_name: lutan_postgres
    environment:
      - POSTGRES_USER=lutan
      - POSTGRES_PASSWORD=lutan
    # ports:
    #   - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    container_name: lutan_backend
    environment:
      - POSTGRES_USER=lutan
      - POSTGRES_PASSWORD=lutan
      - POSTGRES_DB=lutan
      - POSTGRES_HOST=postgres
      - TZ=Asia/Shanghai
    # ports:
    #   - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./media:/Lutan-backend/media
      - ./assets:/Lutan-backend/assets
      - ./backend/logs:/var/log/gunicorn
      - ./backend/wait_for_db.sh:/Lutan-backend/wait_for_db.sh

    command: bash -c "chmod a+x ./wait_for_db.sh &&
      ./wait_for_db.sh &&
      python manage.py migrate &&
      python manage.py collectstatic --clear --no-input &&
      gunicorn Lutan.wsgi -c gunicorn.conf.py"

  frontend:
    build: ./frontend
    restart: always
    container_name: lutan_frontend
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./media:/media
      - ./assets:/assets
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/logs:/var/log/nginx
